### ISSUE TITLE
Make v2 the default branch

### ISSUE THREAD

**Issue by ojongerius** [zorkian/go-datadog-api#101]
As of 11 hours ago Terraform (master, unreleased) uses the v2 branch, via https://github.com/hashicorp/terraform/commit/23103166669afe2b25c094c5b5aff152ac53bc3e

I think we are ready to cut over make v2 the default branch. @zorkian onboard with that?

**Comment by zorkian** [comment]
Wow! That was fast.

And yes, I'm on board, we probably want to update the README to mention that v1 is still available on the branch etc. That way people can get it if they need it and such when they see that their build is breaking. (Although I don't have any idea how many people use this library beyond the Terraform stuff.)

**Comment by ojongerius** [comment]
Ok I've:
* Branch v1 is new, I've created tag v1.1 in it and we could use it to push fixes too.
* Branch v2 now has a new tag, v2.1
* Master now points to 267f4d3cb12d1eb1895d4b7a7893cf37e4213dd7 `git branch -f master 267f4d3cb12d1eb1895d4b7a7893cf37e4213dd7`

I'm not sure if there is much point in having branch v2 around, what do you think?

**Comment by zorkian** [comment]
No, don't need a branch for it.

**Comment by ojongerius** [comment]
Cool, removed branch v2 and go getting `gopkg.in/zorkian/go-datadog-api.v2` will now get tag v2.1
