### ISSUE TITLE
Tag v2.2

### ISSUE THREAD

**Issue by bshelton229** [zorkian/go-datadog-api#107]
Could we tag v2.2. We'd like to implement some features from https://github.com/zorkian/go-datadog-api/pull/106 into terraform and I think we need a new tag for gopkg.in.

Datadog did update the documentation:
https://github.com/DataDog/documentation/issues/1249

Thanks!

**Comment by zorkian** [comment]
Done, 2.2 has been tagged. Sorry for the delay here!
