### ISSUE TITLE
Push update to gopkg.in/zorkian/go-datadog-api.v2

### ISSUE THREAD

**Issue by travisjeffery** [zorkian/go-datadog-api#113]
@zorkian can you push an update to gopkg.in/zorkian/go-datadog-api.v2 with https://github.com/zorkian/go-datadog-api/pull/109? I need to add a feature to Terraform's DD provider. Thanks.

**Comment by zorkian** [comment]
Done, v2.3 tagged and available. Sorry for the delay -- was out of country!
