### ISSUE TITLE
Snapshot & QueryMetrics inconsistencies

### ISSUE THREAD

**Issue by nyanshak** [zorkian/go-datadog-api#114]
I've been trying to use both the Snapshot func (from snapshot.go) and the QueryMetrics func (from series.go) and ran into issues trying to use QueryMetrics.

Example:

```go
query := "sum:aws.elb.request_count{*}.as_count().rollup(sum)"

// assume client is valid initialized datadog api client and start / end are valid time.Time values
_, err := client.Snapshot(query, start, end, "")
if err != nil {
    fmt.Println(err)
}

_, err = client.QueryMetrics(start.Unix(), end.Unix(), query)
if err != nil {
    fmt.Println(err)
}
```

The implementation of Snapshot url-encodes the query value, whereas QueryMetrics just does:
``` ..."?query="+query...```
So unless you url-encode the query before sending to QueryMetrics, you'll get a 400 back from Datadog.

Possible solutions:
* Document this different behavior in a comment / godoc somehow
* Change implementation of QueryMetrics to match Snapshot
* Change implementation of Snapshot to match QueryMetrics

I'd personally prefer option 2 (change implementation of QueryMetrics to match Snapshot) as it results in a simpler interface and easier to use for clients trying to use it.

I'll add a pull request with that approach.

**Comment by zorkian** [comment]
Thanks for catching -- this change makes sense. I agree that making it simple for the user i.e. the library does the URL-encoding automatically makes the most sense.
