### ISSUE TITLE
Hosts: Muting a host

### ISSUE THREAD

**Issue by simar7** [zorkian/go-datadog-api#121]
Hello,

Thanks for the awesome go bindings for DataDog. I was curious if there was something on the roadmap for adding support for muting/unmuting a host? Currently DataDog supports it like so: https://docs.datadoghq.com/api/?lang=console#hosts-mute

If there isn't, I can submit a PR to get it going.

Cheers,
Simar

**Comment by simar7** [comment]
I've opened up a PR for this feature: https://github.com/zorkian/go-datadog-api/pull/123

**Comment by zorkian** [comment]
Resolved by #123 ... and thanks for doing this. Appreciate the initiative, and so quick!
