### ISSUE TITLE
Support `access_role` field for user object

### ISSUE THREAD

**Issue by nyanshak** [zorkian/go-datadog-api#126]
Proposal: Replace `is_admin` with `access_role`.

Reasons:

There are currently 3 types of users `ro` (read-only), `st` (standard), and `adm` (admin). The library as-is (with `is_admin` field) only supports `st` (`is_admin` set to false) and `adm` (`is_admin` set to true). This means that read-only users will automatically be changed to standard users when this library is used to update a user, even if that was not the intention.

Why not keep both `is_admin` and `access_role`?

This results in confusing behavior, because it's unclear to users what the behavior is if I set `is_admin` to true and `access_role` to `st`. Do I get a standard user that somehow has admin access? Do I get a standard user? Do I get an admin user? The correct answer is that `access_role` takes precedence and `is_admin` will be ignored if they conflict.

```
| is_admin | access_role | resulting user |
| false    | ro          | ro             |
| true     | ro          | ro             |
| false    | st          | st             |
| true     | st          | st             |
| false    | adm         | adm            |
| true     | adm         | adm            |
```

@zorkian Let me know what you think about the proposal.

**Comment by zorkian** [comment]
We can't break the API (which happens when methods are removed) unless we're rolling a new major version. I don't think we really want to do that for this particular change.

I agree that supporting both is_admin and access_role is confusing. Is the logic table you provided based on testing with how DataDog actually interprets the situation?

The easiest is just to allow both, but I think that it might be worth introducing some way of deprecating a field and saying 'you should convert to use this other field, this field will go away next major version'. That way people see it in their logs if they're using it and know about the unexpected behavior.

Thoughts?

**Comment by nyanshak** [comment]
The truth table is based on my testing of the actual API behavior.

I like the idea of somehow marking the field as deprecated and logging. Agreed that it would require a major version change to remove the field.

**Comment by nyanshak** [comment]
@zorkian 

I see two options:

1. Add a comment to the struct field itself stating that this field is deprecated and will be removed in the next major version.
2. Update gen-accessors to support some custom annotation, something like:
```go
type X struct {
    thing *string `json:"thing,omitempty" deprecated:"remove"`
    // OR maybe like this:
    thing *string `json:"thing,omitempty" go-datadog-api:"deprecated"`
}
```
With option 2, it would be possible to make the generated accessors add a `fmt.Println` or `log.Info`(or whatever) to say "hey this field `field` is deprecated and will be removed in the next major go-datadog-api library".

Option 1:
Pro: Simple to implement, still adds documentation in code that field is deprecated.
Con: Makes it non-obvious if users upgrade without reading the code that a field may be removed.

Option 2:
Pro: This might be nicer to users.
Con:
* Much more difficult to implement. If we ever need to deprecate non-pointer types, there's not a clear path to do it (since the generators only generate functions for the pointers). Having two different ways to do deprecation will be confusing.
* Users that are accessing fields without the generators (since the fields are still exported and can be used directly) will not as easily discover that the field is deprecated (would be easier to see with a big big DEPRECATED comment).

I prefer Option 1 (simple deprecated comment), but if you'd prefer Option 2, I could try to update the generator.

I went ahead and updated the PR to add back in IsAdmin, along with a comment noting its deprecation.
