### ISSUE TITLE
Add goreportcard badge

### ISSUE THREAD

**Issue by ojongerius** [zorkian/go-datadog-api#132]
See https://goreportcard.com/report/github.com/zorkian/go-datadog-api  for the current score.

@tariq1890 might this something you would be willing to add?

**Comment by tariq1890** [comment]
Sure!

**Comment by ojongerius** [comment]
Legend!

**Comment by ojongerius** [comment]
Thanks @tariq1890!

**Comment by tariq1890** [comment]
Glad to help :)
