### ISSUE TITLE
Response from metrics endpoint may contain null values

### ISSUE THREAD

**Issue by jkorzekwa-atlassian** [zorkian/go-datadog-api#145]
Currently the values returned from the metrics endpoint are expected to be an array of ints with the first element being the timestamp and the second element being the value, But sometime the value is "null", which go is being set to 0 by golang due to the type being int in series.go:
`type DataPoint [2]float64`
I believe changing the array type to a pointer`*float64` should fix the issue and allow the value to be null.

**Comment by ojongerius** [comment]
Thanks for raising this issue!

This sounds plausible, would you be willing and able to raise a PR for this?

**Comment by ojongerius** [comment]
Released in https://github.com/zorkian/go-datadog-api/releases/tag/v2.8.5

@jkorzekwa-atlassian good to close?

**Comment by yfronto** [comment]
Verified it's closable from @jkorzekwa-atlassian
