### ISSUE TITLE
datadog.DataPoint type was changed within the same minor version (2.8)

### ISSUE THREAD

**Issue by dcu** [zorkian/go-datadog-api#154]
Thus breaking builds depending on the 2.8 
https://github.com/zorkian/go-datadog-api/blob/v2.8.4/series.go#L18
vs
https://github.com/zorkian/go-datadog-api/blob/v2.8.5/series.go#L18

We already updated the code but this is not ideal

**Comment by ojongerius** [comment]
I'm sorry to hear that @dcu! This is my bad, apologies!

@zorkian what do you think is the way forward here? We could remove v2.8.5 and cut v2.9.1, which is more correct, however I'm not a super fan of removing releases after they have been published. So I guess we need to decide what is worse: a breaking change in a minor version bump vs removing a release after it's been published.

@dcu just out of interest, what project are you working on, is it open or closed source?

**Comment by dcu** [comment]
hi, it's closed source

**Comment by apowers** [comment]
https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version

**Comment by zorkian** [comment]
Sorry for the slow response here -- yeah, I agree with the semver docs, we should just rev 2.8.6 with the fix (or remove the backwards incompatibility) and a note in the changelog. We can then cut 2.9.1 with the actual change?

**Comment by ojongerius** [comment]
@zorkian sounds like a plan.

I've cut and pushed both https://github.com/zorkian/go-datadog-api/releases/tag/v2.8.6 and https://github.com/zorkian/go-datadog-api/releases/tag/v2.9.1.

Again, apologies for the inconvenience caused!
