### ISSUE TITLE
Feature Request: AWS Integration

### ISSUE THREAD

**Issue by iancward** [zorkian/go-datadog-api#159]
It looks like the Datadog API [supports](https://docs.datadoghq.com/api/?lang=python#aws) configuring the AWS integration. It would be nice if this was updated to provide support for that.

**Comment by yfronto** [comment]
Thanks for requesting. With the other integrations already there as examples, I think it's pretty straight-forward to do this. As such, I'll tag it as a good first issue.

**Comment by ojongerius** [comment]
Fixed in #162
