### ISSUE TITLE
How do you query metrics?

### ISSUE THREAD

**Issue by winhowes** [zorkian/go-datadog-api#17]
In datadog's api they mention you can query metrics (http://docs.datadoghq.com/api/#metrics-query). Looking through your docs, I couldn't find anything to do that. I saw `SearchMetrics`, but that didn't query timeseries data.

**Comment by zorkian** [comment]
Looks like nobody has implemented that method yet. Should be pretty trivial though, about 5 lines of code in `series.go` if you want to take a crack at it.

**Comment by winhowes** [comment]
I've made a PR, tested it against my own stuff and found it works: https://github.com/zorkian/go-datadog-api/pull/18

**Comment by zorkian** [comment]
Merged -- thank you! Closing this :)
