### ISSUE TITLE
Errors reported in JSON response are ignored

### ISSUE THREAD

**Issue by knyar** [zorkian/go-datadog-api#170]
It seems that in some cases Datadog API can return an error in a response with HTTP code 200. In this case the JSON response seems to have the `status` field set to `error` with the specific error returned in the `error` field. Here's an example: https://knyar.net/paste/raw/9d6b2d1a.txt

This behavior contradicts [API documentation](https://docs.datadoghq.com/api/) that says "API uses HTTP status codes to indicate the success or failure of a request". I have reported this issue to Datadog ([issue 155764](https://help.datadoghq.com/hc/en-us/requests/155764) that is probably only visible to me), and got the following response:

> There is a larger discussion ongoing right now towards reworking the API I have added your notes and recommendations to this discussion, but as there is no development planned in the short term, I am going to mark this ticket as closed for now, but your details are still attached to this project and I will reach out once it is closer to development.

So it seems like they don't have any immediate plans to fix this. I've asked them to at least update API documentation to reflect this behavior, however this has not yet been done.

Currently this library does not handle errors communicated in such way, and returns an empty successful response. I believe we need to return an error instead.

**Comment by ojongerius** [comment]
@knyar thanks for this!

Could you please raise an issue at Datadog? It would be great, and probably trivial to fix  in their API.
