### ISSUE TITLE
List all dashboards does not include all fields

### ISSUE THREAD

**Issue by mnaboka** [zorkian/go-datadog-api#185]
[DashboardLite](https://github.com/zorkian/go-datadog-api/blob/master/dashboards.go#L164-L169) structure has very limited number of fields.

I need just one additional field which is `modified`, but ideally i think we need all of them.
Was there a reason not all fields are exported?

I can also open a PR to address this, but i want to hear your feedback first.

Thanks

**Comment by ojongerius** [comment]
Hi @mnaboka! I'm not sure what the reason for this is, the current version of the `DashboardLite` struct is very similar to the initial commit by @zorkian.

Looks like `Dashboard` could do with an update too, `width`, `height`, `read_only` are not included.

**Comment by mnaboka** [comment]
@ojongerius i need to detect if/when dashboard was modified.

**Comment by ojongerius** [comment]
@mnaboka that makes sense, be great if you could raise a PR for that! 🙇

**Comment by mnaboka** [comment]
@ojongerius i opened a [PR 186](https://github.com/zorkian/go-datadog-api/pull/186), would be nice if you'd have a look.

Also it seems that CI is failing, but the tests pass, i am not sure if CI was broken on master or my change did something to it?

Thanks

**Comment by ojongerius** [comment]
Went in with https://github.com/zorkian/go-datadog-api/releases/tag/v2.17.0 

Thanks for your contribution @mnaboka!
