### ISSUE TITLE
Broken Go 1.7 and 1.8 builds

### ISSUE THREAD

**Issue by nyanshak** [zorkian/go-datadog-api#189]
Travis CI builds fail because golint no longer supports Go 1.7 and 1.8. Technically 1.9 is no longer supported, but still works. See [golint release policy](https://golang.org/doc/devel/release.html#policy).

Proposed fixes:

* Make Go-version-specific imports / pin golint version to support 1.7 and 1.8
* Drop 1.7 and 1.8 from builds

I propose following option 2 (drop 1.7 / 1.8). In addition, I suggest we follow the Go release policy and support only the last two major releases (1.10 and 1.11).

I'll raise a PR to change the builds based on the decision in this thread.

cc @zorkian / @yfronto

**Comment by yfronto** [comment]
I'm okay dropping 1.7 and 1.8 from the tests.

**Comment by nyanshak** [comment]
#191 merged to fix this
