### ISSUE TITLE
Support for Synthetics (external moitoring)

### ISSUE THREAD

**Issue by dharada1** [zorkian/go-datadog-api#204]
Requesting support for Synthetics. (external monitoring)

<img width="1625" alt="2019-01-25 11 24 31" src="https://user-images.githubusercontent.com/6387224/51722077-8b41b300-2097-11e9-95a0-5a509f5bdefd.png">

Related to : https://github.com/terraform-providers/terraform-provider-datadog/issues/147

**Comment by dharada1** [comment]
I'll do it
https://github.com/zorkian/go-datadog-api/pull/205

**Comment by dharada1** [comment]
at #205 

I started to write integration test, 
and I found synthetics is still closed beta.

It means if I add integration test, 
`make testacc` would fails on master (Travis CI) & other developers environment.
( unless they applied to beta https://app.datadoghq.com/synthetics/beta )

I think we should wait at least synthetics become public beta.

**Comment by ojongerius** [comment]
Awesome, thanks for catching that!

**Comment by btoueg** [comment]
Hello @dharada1, Synthetics is now public! 🎉 you should be able to publish your integration test.

Don't expect the same stability from the synthetics end points than from other officially documented endpoints (see official documentation here https://docs.datadoghq.com/api/)

**Comment by bkabrda** [comment]
Support for /v1/synthetics was merged in https://github.com/zorkian/go-datadog-api/pull/228 so I'm closing this issue.
