### ISSUE TITLE
Support for Host totals

### ISSUE THREAD

**Issue by dharada1** [zorkian/go-datadog-api#214]
document : https://docs.datadoghq.com/api/?lang=bash#host-totals

`GET https://api.datadoghq.com/api/v1/hosts/totals`

Example Request
```
api_key=<YOUR_API_KEY>
app_key=<YOUR_APP_KEY>

curl -G "https://api.datadoghq.com/api/v1/hosts/totals" \
     -d "api_key=${api_key}" \
     -d "application_key=${app_key}"
```

Example Response

```
{"total_up":1750,"total_active":1759}
```

**Comment by bkabrda** [comment]
Implemented in https://github.com/zorkian/go-datadog-api/pull/267 - closing this issue now.
