### ISSUE TITLE
`PUT https://api.datadoghq.com/api/v1/user/<USER_ID>` Seems to be more paranoid now.

### ISSUE THREAD

**Issue by brendanjerwin** [zorkian/go-datadog-api#221]
We've started getting `400 Bad Request: {"errors": ["Additional properties are not allowed (u'handle' was unexpected)"]}` from the Terraform Datadog provider.

I suspect that the server has recently gotten more paranoid and is now erroring. 
I assume this line: https://github.com/zorkian/go-datadog-api/blob/master/users.go#L88 results in a JSON payload that includes `handle`.

I'm willing to work on a solution. Any guidance? (My first inclination is a struct specifically for the update user action and a factory to create one from the common user struct.)

**Comment by bkabrda** [comment]
Fixed in #222. Closing this issue now.
