### ISSUE TITLE
Support new dashboard api

### ISSUE THREAD

**Issue by atsushi-ishibashi** [zorkian/go-datadog-api#229]
https://docs.datadoghq.com/api/?lang=bash#dashboards
I'd like to take over this issue.

Unfortunately, `Dashboard` struct is used for TimeboardAPI 😢
If `Dashboardv2` will be applied, it will confuse with api version `v1`.

Do anyone have a good idea?

**Comment by bkabrda** [comment]
The support for new dashboard API was added in https://github.com/zorkian/go-datadog-api/pull/231 and to preserve backwards compatibility the new struct is called `Board`. I guess this can be closed now, as the original request was fulfilled.
