### ISSUE TITLE
/v1/dashboard to get all dashboards is missing

### ISSUE THREAD

**Issue by Morsicus** [zorkian/go-datadog-api#253]
Hey, 

I think this route https://docs.datadoghq.com/api/?lang=python#get-all-dashboards is not implemented in the library, right?

May i help? Or maybe i'm missing something in the documentation :/. 

In any case, please let me know.

**Comment by bkabrda** [comment]
Hey!

Yeah, it's not. TBH I'm not sure why that's the case, but I'd be happy to review a PR if you want to submit support for this. You'd need to add it to https://github.com/zorkian/go-datadog-api/blob/master/boards.go, it should be pretty straightforward.

Thanks for reaching out!
