### ISSUE TITLE
Feature Request: Webhook Integration support

### ISSUE THREAD

**Issue by krish7919** [zorkian/go-datadog-api#264]
I was looking to add the Webhook resource in the `terraform-datadog-provider`, however it depends on this library which does not implement webhook integration.

Would it be possible to add that?

I can help with a PR.

**Comment by bkimbrough-bw** [comment]
I created a related Issue on the Terraform side as I'd like to see this too. See https://github.com/terraform-providers/terraform-provider-datadog/issues/344

**Comment by krish7919** [comment]
This is handled with: https://github.com/zorkian/go-datadog-api/pull/265

**Comment by bkimbrough-bw** [comment]
> This is handled with: #265

My bad on the PR, should have looked for yours instead before doing a PR myself.

**Comment by bkabrda** [comment]
Fixed in #300. Closing this issue.
