### ISSUE TITLE
https://app.datadoghq.com/api/v1/validate endpoint returns HTML for non-valid api keys

### ISSUE THREAD

**Issue by tonglil** [zorkian/go-datadog-api#286]
```
$ curl -L -X GET -H 'Content-Type: application/json' -H "DD-API-KEY: invalid" "https://app.datadoghq.com/api/v1/validate"
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

This breaks the library by returning a parsing error `invalid character '<' looking for beginning of value` instead of `false` for https://godoc.org/gopkg.in/zorkian/go-datadog-api.v2#Client.Validate.

**Comment by bkabrda** [comment]
Closing as per the above comment. Feel free to reopen if you're still experiencing issues.
