### ISSUE TITLE
getDashboards and other operations use deprecated endpoints

### ISSUE THREAD

**Issue by blaines** [zorkian/go-datadog-api#298]
https://github.com/zorkian/go-datadog-api/blob/master/dashboards.go#L274-L280
https://docs.datadoghq.com/dashboards/guide/timeboard-api-doc/?tab=python
https://docs.datadoghq.com/api/?lang=bash#timeboards

Datadog says:
> This endpoint is outdated. Use the new Dashboard endpoint instead. Documentation for old endpoints is available in the Screenboard API documentation.

This affects all calls to `/dash` or `/screen`.

**Comment by bkabrda** [comment]
Hey 👋 thanks for reaching out. We're not planning to modify the old functionality/calls. Rather, we implemented the new `GetBoard`, `CreateBoard`, ... endpoints that use the new `dashboards API (implemented in `boards.go`). Feel free to give these a try if you want/need to use the new API.
