### ISSUE TITLE
Is any plan to support "/v1/dashboard" API?

### ISSUE THREAD

**Issue by provcristianmaluenda** [zorkian/go-datadog-api#308]
Is any plan to support `/v1/dashboard` API?

I realized the current implementation for Dashboard uses the old API, which is `outdated` :(.

**Comment by inductor** [comment]
@zorkian please 🙏

**Comment by bkabrda** [comment]
Hey folks, the new dashboards API has been supported for quite a while, take a look at `boards.go` and `board_widgets.go` - is that what you're looking for?
