### ISSUE TITLE
[Feature request] Force deletion of monitors

### ISSUE THREAD

**Issue by Towerthousand** [zorkian/go-datadog-api#310]
Could we support calling monitor deletion with the `force` flag set?

As per the docs: https://docs.datadoghq.com/api/?lang=bash#delete-a-monitor

This would potentially allow this to be used from the Terraform provider implementation, which we would solve https://github.com/terraform-providers/terraform-provider-datadog/issues/439

**Comment by bkabrda** [comment]
Merged in #311, closing. Thanks!
