### ISSUE TITLE
Allow insecure certificates is not supported

### ISSUE THREAD

**Issue by matt-canty-dragon** [zorkian/go-datadog-api#322]
`allow_insecure` is not supported in Synthetics.

Expected as _option_ here:
https://github.com/zorkian/go-datadog-api/blob/master/synthetics.go#L54-L63

Documentation on the topic:
https://docs.datadoghq.com/synthetics/api_tests/?tab=httptest

![image](https://user-images.githubusercontent.com/56073682/79842607-f704ef80-83b0-11ea-805f-19931609cfff.png)

**Comment by nsuarezcanton** [comment]
I've made a quick PR for this issue: https://github.com/zorkian/go-datadog-api/pull/324. Thanks for surfacing this!
