### ISSUE TITLE
CreateUser API

### ISSUE THREAD

**Issue by ge1st** [zorkian/go-datadog-api#37]
Hi guys,

The [API reference for DD](http://docs.datadoghq.com/api/) shows a `POST api/v1/user` to create a new user. This client has the `invite_users` call in its stead.

I assume the DD API changed over time and that's why it's not here. Any reason for me not to add it in with a PR?

Thanks.

**Comment by zorkian** [comment]
No reason! After the initial implementation pass, most of the API methods in this project have gotten added over time when people need them.
