### ISSUE TITLE
Graphs appearance customisation

### ISSUE THREAD

**Issue by smeshkov** [zorkian/go-datadog-api#52]
**Context**
When user defines graph in Datadog it provides him a handful of ways to customise output. So devs want the same functionality to be reflected in the API's.

**Problem**
Currently devs can only provide "q" and "satcked" arguments to request clause. But what if we want something more?

**Task**
Expose other arguments to the APIs.
Example of rich query:
```
{
  "text_align": "left",
  "autoscale": false,
  "custom_unit": "%",
  "precision": 3,
  "viz": "query_value",
  "requests": [
    {
      "q": "<some_huge_query_here>",
      "aggregator": "sum",
      "conditional_formats": [
        {
          "palette": "white_on_green",
          "comparator": ">",
          "custom_bg_color": null,
          "value": 99.99,
          "invert": false,
          "custom_fg_color": null
        },
        {
          "palette": "white_on_yellow",
          "comparator": ">=",
          "custom_bg_color": null,
          "value": 99,
          "invert": false,
          "custom_fg_color": null
        },
        {
          "palette": "white_on_red",
          "comparator": "<",
          "custom_bg_color": null,
          "value": 99,
          "invert": false,
          "custom_fg_color": null
        }
      ]
    }
  ]
}
```

**Comment by smeshkov** [comment]
@zorkian @ojongerius is there a way to open a pull request for your project? I've just branched out of master and added some stuff, but when I try to push branch to origin I see:
```
$ git push --set-upstream origin 52-graph-custom-appearance
ERROR: Permission to zorkian/go-datadog-api.git denied to smeshkov.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by zorkian** [comment]
Yeah, you use the GitHub web site. Usual flow is,

1. Fork the project
2. Create a branch on your fork and push to it
3. Go to github.com and click the 'create pull request' button

https://help.github.com/articles/creating-a-pull-request/ has more details.

Good luck and thanks! :)

--
Mark Smith
mark@qq.is


On Thu, Aug 11, 2016, at 09:38 PM, Sergey wrote:
> @zorkian[1] @ojongerius[2] is there a way to open a pull request for
> your project? I've just branched out of master and added some stuff,
> but when I try to push branch to origin I see:


> $ git push --set-upstream origin 52-graph-custom-appearance ERROR:
> Permission to zorkian/go-datadog-api.git denied to smeshkov. fatal:
> Could not read from remote repository.  Please make sure you have the
> correct access rights and the repository exists.
>
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].
>


Links:

  1. https://github.com/zorkian
  2. https://github.com/ojongerius
  3. https://github.com/zorkian/go-datadog-api/issues/52#issuecomment-239359443

**Comment by smeshkov** [comment]
Got it, thanks! Here is a PR: https://github.com/zorkian/go-datadog-api/pull/53

**Comment by ojongerius** [comment]
Can close?

**Comment by zorkian** [comment]
Oh yes, good catch :)
