### ISSUE TITLE
Schedule integration test runs

### ISSUE THREAD

**Issue by ojongerius** [zorkian/go-datadog-api#74]
This should be valuable enough, we could use https://docs.travis-ci.com/user/cron-jobs . 

- [x] arrange sandbox credentials at Datadog.
- [ ] setup a schedule for these builds.

**Comment by ojongerius** [comment]
Have created test account, have requests them to turn it into one that sticks around so we can use it for daily integration test runs.

**Comment by ojongerius** [comment]
@zorkian I won't be able to finish this work, and have unassigned myself. I've created a "help wanted" label, with a hideous colour, I blame you using the nice green one for "contributor friendly" 😉

**Comment by zorkian** [comment]
Hah, no worries. Feel free to move colors around if you really want...!
--
Mark Smith
mark@qq.is


On Sun, Nov 12, 2017, at 01:12 PM, Otto Jongerius wrote:
> @zorkian[1] I won't be able to finish this work, and have unassigned
> myself. I've created a "help wanted" label, with a hideous colour, I
> blame you using the nice green one for "contributor friendly" 😉> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/zorkian
  2. https://github.com/zorkian/go-datadog-api/issues/74#issuecomment-343768154
