### ISSUE TITLE
Label open issues

### ISSUE THREAD

**Issue by ojongerius** [zorkian/go-datadog-api#80]
@zorkian could you please add some labels on the open issues? Would make it easier to see which issues are awaiting response, which could do with some help, what is easy etc. Happy to do it for you if you give me the power to do so.

Labels I'd like to see are "awaiting response", "contributor friendly", "bug", and "enhancement".

**Comment by zorkian** [comment]
I invited you as a collaborator -- not 100% sure what powers that gives you. I did create the labels and pruned the others, though. Great idea, thank you!

**Comment by ojongerius** [comment]
Nice work. Thanks!
