### ISSUE TITLE
Align with Datadog on their fork

### ISSUE THREAD

**Issue by ojongerius** [zorkian/go-datadog-api#88]
I noticed their is a fork at https://github.com/DataDog/go-datadog-api, and I'm curious if Datadog contacted you, @zorkian?

I noticed https://github.com/ufoot commit a change, and I'm wondering what the vision is here If the code of up and downstream start to deviate that would be a shame.

**Comment by zorkian** [comment]
No, I haven't had any communication with them. PS I will get back to you on the other PR, it's looking good so far. I'm mid-review but haven't finished yet, sorry!

**Comment by ojongerius** [comment]
Interesting, thanks. Good to know you are on the PR :)
